swagger: "2.0"

info:
  version: "1.0"
  title: Music Sheet Conversion Tool
  description: Ziqi's tool to convert the music sheet into another Major

schemes:
  - https
host: convertmusicsheet.api
basePath: /openapi/tools/conversion/sheets/music

paths:
  /origin:
    get:
      summary: Gets Original Music Sheets
      description: Returns a list of original music sheet
      parameters:
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
      responses:
        200:
          description: A list of original music sheet
          schema:
            $ref: "#/definitions/MusicSheetList"
        404:
          $ref: "#/responses/NotFoundError"
        500:
          $ref: "#/responses/InternalError"
    post:
      summary:  Add a new music sheet (Origin)
      description:  Add a new music sheet in the server
      parameters:
        - name: musicSheet
          in: body
          description: Create a new music sheet
          schema:
            $ref: "#/definitions/MusicSheet"
      responses:
        204:
          description:  The music sheet is created successfully
        400:
          $ref: "#/responses/ExecutionError"

  /origin/{musicName}:
    get:
      summary:  Get the specific music sheet
      description:  Return the specific music sheet for its name
      parameters:
        - $ref: "#/parameters/musicName"
        - $ref: "#/parameters/key"
        - $ref: "#/parameters/singer"
        - $ref: "#/parameters/composer"
        - $ref: "#/parameters/lyricist"
      responses:
        200:
          description:  The Music Sheet is returned successfully!
          schema:
            $ref: "#/definitions/MusicSheet"
        404:
          $ref: "#/responses/NotFoundError"
        500:
          $ref: "#/responses/InternalError"

  /converted:
    get:
      summary: Gets Converted Music Sheets
      description: Returns a list of converted music sheet
      parameters:
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
      responses:
        200:
          description:  A list of converted music sheet
          schema:
            $ref: "#/definitions/MusicSheetList"
        404:
          $ref: "#/responses/NotFoundError"
        500:
          $ref: "#/responses/InternalError"

  /converted/{musicName}:
    get:
      summary:  Get the specific music sheet
      description:  Return the specific music sheet for its name
      parameters:
        - $ref: "#/parameters/musicName"
        - $ref: "#/parameters/key"
        - $ref: "#/parameters/singer"
        - $ref: "#/parameters/composer"
        - $ref: "#/parameters/lyricist"
      responses:
        200:
          description:  The Music Sheet is returned successfully!
          schema:
            $ref: "#/definitions/MusicSheet"
        404:
          $ref: "#/responses/NotFoundError"
        500:
          $ref: "#/responses/InternalError"

definitions:
  MusicSheetList:
    type: array
    items:
      $ref: "#/definitions/MusicSheet"
      # msid: # Music Sheet ID
      #   type: string

  MusicSheet:
    required:
      - musicName
      - key
    properties:
      musicName:
        type: string
      key:
        type: string
      timeSignature:
        type: string
      tempo:
        type: string
      melody:
        type: string
      lyrics:
        type: string
      composer:
        type: string
      lyricist:
        type: string
      singer:
        type: string

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string

parameters:
  pageSize:
    name: pageSize
    in: query
    description:  Number of music sheets returned
    type: integer
  pageNumber:
    name: pageNumber
    in: query
    description:  Page number
    type: integer
  musicName:
    name: musicName
    in: path
    required: true
    description:  The music sheet's name
    type: string
  key:
    name: key
    in: query
    required: false
    description:  The key of music
    type: string
  singer:
    name: singer
    in: query
    required: false
    description:  The singer of the music
    type: string
  composer:
    name: composer
    in: query
    required: false
    description:  The composer of the music
    type: string
  lyricist:
    name: lyricist
    in: query
    required: false
    description:  The lyricist of the music
    type: string

responses:
  ExecutionError:
    description:  Failed to take executions on Database
    schema:
      $ref: "#/definitions/Error"

  NotFoundError:
    description:  Not Found Error
    schema:
      $ref: "#/definitions/Error"

  InternalError:
    description:  Internal Error
    schema:
      $ref: "#/definitions/Error"