swagger: "2.0"

info:
  version: "1.0"
  title: Music Sheet Conversion Tool
  description: Ziqi's tool to convert the music sheet into another Major

schemes:
  - https
host: convertmusicsheet.api
basePath: /openapi/tools/conversion/sheets/music

paths:
  /origin:
    get:
      summary: Gets Original Music Sheets
      description: Returns a list of original music sheet
      parameters:
        - name: pageSize
          in: query
          description:  Number of music sheets returned
          type: integer
        - name: pageNumber
          in: query
          description:  Page Number
          type: integer
      responses:
        200:
          description: A list of original music sheet
          schema:
            type: array
            items:
              required:
                - musicName
                - key
              properties:
                musicName:
                  type: string
                key:
                  type: string
                timeSignature:  #拍子
                  type: string
                tempo:
                  type: string
                melody:
                  type: string
                lyrics:
                  type: string
                composer:
                  type: string
                lyricist:
                  type: string
                singer:
                  type: string
                msid: # Music Sheet ID
                  type: string
        404:
          description:  Page Not Found
        500:
          description:  Internal Error
    post:
      summary:  Add a new music sheet (Origin)
      description:  Add a new music sheet in the server
      parameters:
        - name: musicSheet
          in: body
          description: Create a new music sheet
          schema:
            required:
              - musicName
              - key
            properties:
              musicName:
                type: string
              key:
                type: string
              timeSignature:
                type: string
              tempo:
                type: string
              melody:
                type: string
              lyrics:
                type: string
              composer:
                type: string
              lyricist:
                type: string
              singer:
                type: string
      responses:
        204:
          description:  The music sheet is created successfully
        400:
          description:  The music sheet couldn't be created
  /origin/{musicName}:
    get:
      summary:  Get the specific music sheet
      description:  Return the specific music sheet for its name
      parameters:
        - name: musicName
          in: path
          required: true
          description:  The music sheet's name
          type: string
        - name: key
          in: query
          required: false
          description:  The key of music
          type: string
        - name: singer
          in: query
          required: false
          description:  The singer of the music
          type: string
        - name: composer
          in: query
          required: false
          description:  The composer of the music
          type: string
        - name: lyricist
          in: query
          required: false
          description:  The lyricist of the music
          type: string
      responses:
        200:
          description:  The Music Sheet is returned successfully!
          schema:
            required:
              - musicName
              - key
              - timeSignature
              - melody
            properties:
              musicName:
                type: string
              key:
                type: string
              timeSignature:
                type: string
              tempo:
                type: string
              composer:
                type: string
              lyricist:
                type: string
              singer:
                type: string
              melody:
                type: string
              lyric:
                type: string
        404:
          description:  The music sheet is not found!
        500:
          description:  Internal Error
  /converted:
    get:
      summary: Gets Converted Music Sheets
      description: Returns a list of converted music sheet
      parameters:
        - name: pageSize
          in: query
          description:  Number of music sheets returned
          type: integer
        - name: pageNumber
          in: query
          description:  Page number
          type: integer
      responses:
        200:
          description:  A list of converted music sheet
          schema:
            type: array
            items:
              required:
                - musicName
                - key
              properties:
                musicName:
                  type: string
                key:
                  type: string
                timeSignature:  #拍子
                  type: string
                tempo:
                  type: string
                melody:
                  type: string
                lyrics:
                  type: string
                composer:
                  type: string
                lyricist:
                  type: string
                singer:
                  type: string
                msid: # Music Sheet ID
                  type: string
        404:
          description:  Page Not Found
        500:
          description:  Internal Error
  /converted/{musicName}:
    get:
      summary:  Get the specific music sheet
      description:  Return the specific music sheet for its name
      parameters:
        - name: musicName
          in: path
          required: true
          description:  The music sheet's name
          type: string
        - name: key
          in: query
          required: false
          description:  The key of music
          type: string
        - name: singer
          in: query
          required: false
          description:  The singer of the music
          type: string
        - name: composer
          in: query
          required: false
          description:  The composer of the music
          type: string
        - name: lyricist
          in: query
          required: false
          description:  The lyricist of the music
          type: string
      responses:
        200:
          description:  The Music Sheet is returned successfully!
          schema:
            required:
              - musicName
              - key
              - timeSignature
              - melody
            properties:
              musicName:
                type: string
              key:
                type: string
              timeSignature:
                type: string
              tempo:
                type: string
              composer:
                type: string
              lyricist:
                type: string
              singer:
                type: string
              melody:
                type: string
              lyric:
                type: string
        404:
          description:  The music sheet is not found!
        500:
          description:  Internal Error